#cffff0000 Willkommen bei 

#cff0000ff FlyFF Deutschland!!

Wir sind hier in Madrigal, einer wunderschönen und fantastischen Welt!
Bitte sei vorsichtig, denn hier gibt es viele gefährliche Monster.
Wir hoffen, dass ihr diese schöne Welt auch gut behandelt und sie mit euren Freunden teilt!
Daher wünschen wir dir viel Spass bei deinem Abenteuer!


#cffff0000 Die reguläre Serverwartungszeit ist:
#cffff0000 Dienstag morgen zwischen 08:00 und 10:00 Uhr (GMT+1)
#cffff0000 Näheres hierzu findest du in unserem Forum auf www.gpotato.eu

#cffff0000 Für Fragen bezüglich des Supports, schreibe bitte eine Email an gm@gpotato.eu.
